model:
  pretrained: true
  backbone: "efficientnet-b4"
  scope: 512
  merger_inter_out_channels: [256, 128, 64]
  merged_channels: 32

training:
  prefix: "./runs/efnb4_scope512_inter256_128_64_merged32_icdar2015/"
  img_root_dir:
    train: "/mnt/9C5E1A4D5E1A2116/datasets/ICDAR_2015/train_img"
  annotations_root_dir:
    train: "/mnt/9C5E1A4D5E1A2116/datasets/ICDAR_2015/train_gt"
  batch_size: 16
  learning_rate: 0.001
  epochs: 1000
  num_workers: 16
  checkpoint:
    frequency: 500
    max_checkpoints: 5
  multi_gpu: true
  mixed_precision: true
  resume: true
