model:
  pretrained: true
  backbone: "efficientnet-b5"
  scope: 512
  merger_inter_out_channels: [256, 128, 64]
  merged_channels: 32

training:
  prefix: "./runs/efficientnetb5_scope512_inter256_128_64_merged32_icdar2015/"
  img_root_dir:
    train: "../datasets/ICDAR_2015/train_img"
  annotations_root_dir:
    train: "../datasets/ICDAR_2015/train_gt"
  batch_size: 3
  learning_rate: 0.001
  epochs: 1000
  num_workers: 16
  checkpoint:
    frequency: 500
    max_checkpoints: 5
  multi_gpu: false
  mixed_precision: true
  resume: true
