model:
  pretrained: true
  backbone: "xception"
  scope: 512
  merger_inter_out_channels: [128, 64, 32]
  merged_channels: 32

training:
  prefix: "./pths-test_code_refactor/"
  img_root_dir:
    train: "/mnt/9C5E1A4D5E1A2116/datasets/ICDAR_2015/train_img"
  annotations_root_dir:
    train: "/mnt/9C5E1A4D5E1A2116/datasets/ICDAR_2015/train_gt"
  batch_size: 16
  learning_rate: 0.001
  epochs: 1000
  num_workers: 16
  checkpoint:
    frequency: 500
    max_checkpoints: 5
  multi_gpu: true
  mixed_precision: true
  resume: true
